version: "3.6"

networks: 
  backend: 

services:

  nginx:
    image: nginx:1.19.8-alpine
    restart: always
    working_dir: /app/build
    volumes:
      - ./frontend:/app:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  backend:
    image: node:15.12.0-alpine3.10
    restart: always
    command: tail -f /dev/null
    working_dir: /app
    environment: 
      DB_HOST: &db-host db
      DB_TYPE: mysql
      DB_PORT: 3306
    volumes:
      - ./backend:/app:rw
      - ./.env:/.env:ro
    ports:
      - 5001:5000

  db:
    image: mysql:8.0.23
    hostname: *db-host
    volumes: 
      - ./dbdata:/var/lib/mysql:rw
    env_file: ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    ports:
      - 8081:80
    environment:
      PMA_HOST: *db-host
    depends_on:
      - db