version: "3.6"

networks: 
  backend: 

services:

  backend-testing:
    image: node:15.12.0-alpine3.10
    command: yarn test:e2e
    working_dir: /app
    environment: 
      DB_HOST: &db-host db-testing
      DB_TYPE: mysql
      DB_PORT: 3306
      MYSQL_DATABASE: &db-name e2e-testing
      MYSQL_USER: root
      MYSQL_PASSWORD: &db-root-password root
    depends_on: 
      - db-testing
    volumes:
      - ./backend:/app:rw
      - ./.env:/.env:ro

  db-testing:
    image: mysql:8.0.23
    hostname: *db-host
    environment: 
      MYSQL_ROOT_PASSWORD: *db-root-password
      MYSQL_DATABASE: *db-name